# Generated by Django 6.0.2 on 2026-04-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_accountholding_quantity_trade_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cashBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
