# Generated by Django 6.0.2 on 2026-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_account_cashbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runKey', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sourceName', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
