# Generated by Django 6.0.2 on 2026-04-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_processorrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstanding',
            name='cashBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
