# Generated by Django 6.0.2 on 2026-02-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Ticker',
        ),
    ]
