# Generated by Django 6.0.2 on 2026-02-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0002_rename_message_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='text',
            new_name='ticker',
        ),
    ]
